// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audits.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRequestLog = `-- name: CreateRequestLog :one
INSERT INTO request_log (id, method, path, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateRequestLogParams struct {
	ID     uuid.UUID `json:"id"`
	Method string    `json:"method"`
	Path   string    `json:"path"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateRequestLog(ctx context.Context, arg CreateRequestLogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRequestLog,
		arg.ID,
		arg.Method,
		arg.Path,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createResponseLog = `-- name: CreateResponseLog :exec
INSERT INTO response_log (id, status)
VALUES ($1, $2)
`

type CreateResponseLogParams struct {
	ID     uuid.UUID `json:"id"`
	Status int32     `json:"status"`
}

func (q *Queries) CreateResponseLog(ctx context.Context, arg CreateResponseLogParams) error {
	_, err := q.db.Exec(ctx, createResponseLog, arg.ID, arg.Status)
	return err
}
