// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        uuid.UUID        `json:"id"`
	SpaceID   uuid.UUID        `json:"space_id"`
	Author    uuid.UUID        `json:"author"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type RequestLog struct {
	ID        uuid.UUID        `json:"id"`
	Method    string           `json:"method"`
	Path      string           `json:"path"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ResponseLog struct {
	ID        uuid.UUID        `json:"id"`
	Status    int32            `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Space struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Owner     uuid.UUID        `json:"owner"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
